import { defineStyleProps } from '../types/tuple';

export const styleProps = defineStyleProps([
    // 1. Layout
    'display',
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'inset',
    'insetInline',
    'insetBlock',
    'zIndex',

    // 2. Flexbox
    'flex',
    'flexDirection',
    'flexWrap',
    'flexGrow',
    'flexShrink',
    'flexBasis',
    'justifyContent',
    'alignItems',
    'alignContent',
    'alignSelf',

    // 3. Grid
    'gridTemplateColumns',
    'gridTemplateRows',
    'gridTemplateAreas',
    'gridAutoFlow',
    'gridAutoRows',
    'gridAutoColumns',
    'gridColumn',
    'gridRow',
    'gridArea',
    'justifyItems',
    'justifySelf',
    'placeContent',
    'placeItems',
    'gap',
    'rowGap',
    'columnGap',

    // 4. Box model (spacing)
    'margin',
    'marginTop',
    'marginRight',
    'marginBottom',
    'marginLeft',
    'marginInline',
    'marginBlock',
    'padding',
    'paddingTop',
    'paddingRight',
    'paddingBottom',
    'paddingLeft',
    'paddingInline',
    'paddingBlock',

    // 5. Sizing
    'width',
    'minWidth',
    'maxWidth',
    'height',
    'minHeight',
    'maxHeight',
    'aspectRatio',

    // 6. Typography
    'fontFamily',
    'fontSize',
    'fontStyle',
    'fontWeight',
    'lineHeight',
    'letterSpacing',
    'textAlign',
    'textTransform',
    'textDecoration',
    'whiteSpace',
    'textOverflow',
    'wordBreak',
    'overflowWrap',
    'color',

    // 7. Background
    'background',
    'backgroundColor',
    'backgroundImage',
    'backgroundSize',
    'backgroundPosition',
    'backgroundRepeat',
    'backgroundAttachment',
    'backgroundClip',
    'backgroundOrigin',

    // 8. Border
    'border',
    'borderWidth',
    'borderStyle',
    'borderColor',
    'borderRadius',
    'borderTop',
    'borderBottom',
    'borderLeft',
    'borderRight',
    'borderTopColor',
    'borderBottomColor',
    'borderLeftColor',
    'borderRightColor',
    'borderTopWidth',
    'borderBottomWidth',
    'borderLeftWidth',
    'borderRightWidth',
    'borderTopStyle',
    'borderBottomStyle',
    'borderLeftStyle',
    'borderRightStyle',

    // 9. Effects / visual
    'opacity',
    'boxShadow',
    'transform',
    'transformOrigin',
    'transition',
    'transitionProperty',
    'transitionDuration',
    'transitionTimingFunction',
    'transitionDelay',
    'filter',
    'backdropFilter',
    'willChange',

    // 10. Scroll / overflow
    'overflow',
    'overflowX',
    'overflowY',
    'scrollBehavior',
    'scrollSnapType',
    'scrollMargin',
    'scrollPadding',

    // 11. Interaction
    'cursor',
    'pointerEvents',
    'visibility',
] as const);

export type StyleProp = (typeof styleProps)[number];
